# Generated by Django 2.1 on 2018-08-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdalterdata', models.CharField(max_length=6, verbose_name='Cód. Alterdata')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_moved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Movimento')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Veículo')),
                ('chassis', models.CharField(max_length=100, verbose_name='Chassi')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('form_of_payment', models.CharField(max_length=100, verbose_name='Forma de pagamento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_item', to='core.Person')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
