# Generated by Django 2.1 on 2018-08-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('servico', 'SERVIÇO'), ('produto', 'PRODUTO')], max_length=4, verbose_name='Tipo Movimento')),
                ('description', models.CharField(max_length=100, verbose_name='Nome')),
                ('value_moved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Movimento')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
            },
        ),
        migrations.RenameModel(
            old_name='Recibo',
            new_name='Receipt',
        ),
        migrations.AddField(
            model_name='receiptmovimento',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_item', to='core.Receipt'),
        ),
    ]
