# Generated by Django 2.1 on 2018-08-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180809_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmovimento',
            name='kind',
            field=models.CharField(choices=[('servico', 'SERVIÇO'), ('produto', 'PRODUTO')], max_length=10, verbose_name='Tipo Movimento'),
        ),
    ]
