# Generated by Django 2.1 on 2018-08-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180809_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='value_moved',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_item', to='core.Person', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='receiptmovimento',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_item', to='core.Receipt', verbose_name='Recibo'),
        ),
    ]
