# Generated by Django 2.1 on 2018-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180818_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmovimento',
            name='form_of_payment',
            field=models.CharField(choices=[('DINHEIRO', 'dinheiro'), ('CARTÃO DE CRÉDITO', 'cartao_de_credito'), ('CARTÃO DE DÉBITO', 'cartao_de_credito'), ('CHEQUE', 'cheque')], max_length=30, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='receiptmovimento',
            name='kind',
            field=models.CharField(choices=[('ACESSÓRIOS', 'acessorios'), ('SERVIÇO DE INSTALAÇÃO', 'servico_de_instalacao'), ('ACESSÓRIOS E INSTALAÇÃO', 'acessorios_e_instalacao')], max_length=30, verbose_name='Tipo Movimento'),
        ),
    ]
