# Generated by Django 2.1 on 2018-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180818_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmovimento',
            name='form_of_payment',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTAO_DE_CREDITO', 'CARTÃO DE CRÉDITO'), ('CARTAO_DE_DEBITO', 'CARTÃO DE DÉBITO'), ('CHEQUE', 'CHEQUE')], max_length=30, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='receiptmovimento',
            name='kind',
            field=models.CharField(choices=[('ACESSORIOS', 'ACESSÓRIOS'), ('SERVICO_DE_INSTALACAO', 'SERVIÇO DE INSTALACÃO'), ('ACESSORIOS_E_INSTALACAO', 'ACESSÓRIOS E INSTALACÃO')], max_length=30, verbose_name='Tipo Movimento'),
        ),
    ]
