# Generated by Django 2.1 on 2018-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180818_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmovimento',
            name='form_of_payment',
            field=models.CharField(choices=[('DINHEIRO', 'DINHEIRO'), ('CARTÃO DE CRÉDITO', 'CARTÃO DE CRÉDITO'), ('CARTÃO DE DÉBITO', 'CARTÃO DE DÉBITO'), ('CHEQUE', 'CHEQUE')], max_length=30, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='receiptmovimento',
            name='kind',
            field=models.CharField(choices=[('ACESSÓRIOS', 'ACESSÓRIOS'), ('SERVIÇO DE INSTALACÃO', 'SERVIÇO DE INSTALACÃO'), ('CESSÓRIOS E INSTALACÃO', 'ACESSÓRIOS E INSTALACÃO')], max_length=30, verbose_name='Tipo Movimento'),
        ),
    ]
