# Generated by Django 2.1 on 2018-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_receipt_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='observation',
            field=models.CharField(default='Observação dorecibofeita  atoda criaçãoo', max_length=200, verbose_name='Observações'),
            preserve_default=False,
        ),
    ]
