# Generated by Django 2.1 on 2019-05-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181128_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Cliente'),
        ),
    ]
